### ISSUE TITLE
Need test for script isolating logic

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-debug-nodejs#10]
See https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/pull/8/files#r38253599

**Comment by matthewloring** [comment]
@ofrobots Did #31 remove the need for this? We now do everything statically and have no heuristic to resolve ambiguities.

**Comment by ofrobots** [comment]
I agree. I consider this fixed by #31.
