### ISSUE TITLE
'Unable to initialize the debuglet api -- disabling debuglet' should not crash

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-debug-nodejs#126]
ERROR:@google/cloud-debug: Unable to initialize the debuglet api -- disabling debuglet [Error: Could not auto-discover project-id. Please export GCLOUD_PROJECT with your project name]

I am not sure this should be crashing my app.

I am developing locally, I have no intent to use the Debugger here.
I should be able to develop without needing to set GCLOUD_PROJECT with my project name.

**Comment by matthewloring** [comment]
@steren Thank you for reporting this. I've landed a fix in #127.
