### ISSUE TITLE
No debugger available on App Engine flex

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-debug-nodejs#128]
My `app.js` contains `require('@google/cloud-debug');`
I deployed my Node.js app on App Engine flexible.

The debug view says:
The Cloud Debugger could not find any application to debug:
Discovering debuggable applications

The README says:
"If you are using Google App Engine Managed VMs, you do not have to do any additional configuration."

Why isn't the Cloud Debugger available?

**Comment by matthewloring** [comment]
This error message is not generated by our agent and must be coming from the debugger service. Do you see anything in the stdout logs? Relevant log messages should be prefaced with `'@google/cloud-debug'`.

**Comment by steren** [comment]
Ah yes I see:

> ERROR:@google/cloud-debug: Failed to re-register debuggee: Error: A Forbidden error was returned while attempting to retrieve an access token for the Compute Engine built-in service account. This may be because the Compute Engine instance does not have the correct permission scopes specified. The caller does not have permission

**Comment by ofrobots** [comment]
Interesting. The error originates in the google-auth-library [here](https://github.com/google/google-auth-library-nodejs/blob/3b462ba801e80f7896422123be7bbbad596f9c55/lib/auth/computeclient.js#L102). I don't think I have seen this on AppEngine Flex before. I don't see a reason why the request for an auth token from the metadata service should be refused on AppEngine Flex. This may be possible in Compute Engine environment if the VMs weren't created with cloud API access.

@steren: Is there anything special about the configuration of your project? Are your AppEngine VMs Google-managed?

/cc @tbetbetbe.

**Comment by steren** [comment]
My App Engine versions are using `nodejs	Flexible`.
My app.yaml says: 
`vm: true
runtime: nodejs`

I will invite you to the project, so that you can take a look.

**Comment by steren** [comment]
I am still having the issue.

The UI says:
> Stackdriver Debugger is not set up for the default - alpha1 application. Learn more about how to set up here

**Comment by steren** [comment]
In the Logs, I still see:

> "ERROR:@google/cloud-debug: Failed to re-register debuggee: Error: A Forbidden error was returned while attempting to retrieve an access token for the Compute Engine built-in service account. This may be because the Compute Engine instance does not have the correct permission scopes specified. The caller does not have permission"    

and 

> ERROR:@google/cloud-debug: Disabling gcloud debuglet"

**Comment by matthewloring** [comment]
@steren Could you please give me access to your project as well for debugging. I am not able to reproduce this on a fresh project.

**Comment by steren** [comment]
matthewloring@ troubleshooted the issue.

It was due to a hardcoded project ID in my package.json start script, which was not the same project ID as the one I was deploying my code to.

It could have been detected more easily if the error message contained the project ID to which debug tried to connect. I would have spotted that it was not correct.
