### ISSUE TITLE
A script matching the source file was not found loaded on the debuggee

### ISSUE THREAD

**Issue by otymartin** [GoogleCloudPlatform/cloud-debug-nodejs#138]
@matthewloring 
Why do I keep getting this when i set a breakpoint in my server side code?

I linked stackdriver debug in google cloud to my github server code and but I cant set breakpoints. it throws the above error.

**Comment by matthewloring** [comment]
This error is given when there is no deployed script of the same name as the source file in which the snapshot was set. This is most often shown when the deployed application is different from the version of the source on github.

**Comment by matthewloring** [comment]
I'm going to close this for now. Let us know if you have any other questions about the module.

**Comment by melalj** [comment]
I keep getting the same message when I try to get a snapshot. I checked and The version that I'm loading from git is the same as the one deployed.
Am I missing something?

**Comment by matthewloring** [comment]
It's going to be difficult to diagnose the problem without seeing your full project structure. Are you doing any transpilation or compiling of JS?

**Comment by melalj** [comment]
The transpilation is done only for client side JS, but not the server side code.
Is it possible to load the code from a docker image (GCR) instead of a Git repo?

**Comment by matthewloring** [comment]
Currently this is not possible. Are you able to list the files in your deployment? The file path of the file loaded from git (that you are trying to set a breakpoint in) should be a suffix of exactly one of your deployed files.

**Comment by matthewloring** [comment]
This was resolved offline. The `appPathRelativeToRepository` was being set when it should not have been.
