### ISSUE TITLE
Add a website and description to this GitHub repo

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-debug-nodejs#143]
https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/ should display a link to https://cloud.google.com/debugger and have a nice description.

**Comment by ofrobots** [comment]
Fixed. PTAL at the description I used.

**Comment by steren** [comment]
I would be more descriptive: 'Node.js library for Stackdriver Debugger: investigate...'

**Comment by ofrobots** [comment]
Fixed.
