### ISSUE TITLE
Support for es6

### ISSUE THREAD

**Issue by bramski** [GoogleCloudPlatform/cloud-debug-nodejs#150]
`Only files with .js extensions or source maps are supported`

Of course you do support es6 natively for nodejs now without source maps and without transpiling.  But the cloud debug won't support them.

**Comment by matthewloring** [comment]
Cloud debug should work with native es6 code. Do you have a specific example that is not working?

**Comment by JCB-K** [comment]
I'm seeing the same warning. I've got ES6 code that's transpiled before running the application, including the sourcemaps. So `backend/server.js`(ES6 code) is transpiled to `build/{server.js,server.js.map}` (ES5 code). However if I set a breakpoint in the original ES6 file it's never reached.

**Comment by ofrobots** [comment]
@JCB-K: Do you deploy both the original source along with the transpiled source to running instances or only the latter?

**Comment by JCB-K** [comment]
@ofrobots Everything is deployed. By default the transpiled code isn't in the repo but rather generated at runtime. However I also tried committing these files to see if that would solve it, which it didn't.

**Comment by matthewloring** [comment]
@JCB-K I tried to reproduce your example with a project of the structure you described. Breakpoints set in `build/server.js` were hit for me and I did not see the warning message in the original bug description. Would you be able to provide a test case that isn't working?

**Comment by ofrobots** [comment]
Our handling of transpiled source js->js source is indeed not great, but having the transpiled output available to the debug UI would be a workaround (by comitting it in or using local source). We expect to bring in improved js->js transpile support in a future release.

We are really perplexed at the how one would encounter the original error message: "Only files with .js extensions or source maps are supported" with a .js->.js workflow. If there is a reduced test case that shows that problem, that would be very useful to us.

**Comment by JCB-K** [comment]
Definitely, will get back to you about that!

**Comment by matthewloring** [comment]
@JCB-K Any additional information on this?

**Comment by matthewloring** [comment]
Closing this for now. Feel free to reopen if you encounter additional issues with es6 transpilation.
