### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by Splaktar** [GoogleCloudPlatform/cloud-debug-nodejs#160]
This is related to [ES6 support](https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/issues/150) and [Better support transpiled JavaScript](https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/issues/37) but I thought that keeping the TypeScript bits separate might be helpful.

I'm trying to use cloud-debug with TypeScript using the instructions [here](https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/issues/152#issuecomment-251001634). But I figured that I should keep the discussions separated.

We're running in the GAE Flexible Environment with the default NodeJS Runtime.

I'm seeing `Only files with .js extensions or source maps are supported` in the Debug UI when setting a breakpoint in my `.ts` files.

Here's my `tsconfig.json`:

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "outDir": "dist"
  },
  "exclude": [
    "node_modules",
    "typings",
    "coverage"
  ]
}
```

We had to add the following to our `typings.d.ts` file in our root dir:

```

declare module 'request-promise' {
  function requestPromise(options: any): Promise<any>;
  export = requestPromise;
}
declare module 'xml2js' {
  function parseString(xml: string, callback: Function): void;
}
declare module 'google-cloud' {
  import {Readable, Writable} from 'stream';
  class Storage {
    bucket (name: string): StorageBucket;
  }
  class StorageBucket {
    file (name: string): StorageFile;
    getFiles (options: Object, callback: Function): void;
  }
  class StorageFile {
    createReadStream (): Readable;
    createWriteStream (options: any): Writable;
    delete(callback: Function): void;
  }
  class PubSub {
    topic (name: string) : Topic;
    subscription (name: string): any;
    createTopic (name: string, callback: Function): void;
    getTopics (callback: Function): void;
  }
  class Topic {
    publish (message: Object, callback: Function): void;
    subscribe (subscriptionName: string, options: Object, callback: Function): void;
    delete (callback: Function): void;
  }
  class Subscription {
    pull (options: Object, callback: Function): void;
    on (listenerType: string, callback: Function): void;
    removeListener (listenerType: string, Function): void;
  }
  class BigQuery {
    createDataset(id: string, callback: Function): void;
    dataset(id: string): Dataset;
    getDatasets(query: Object, callback: Function): void;
  }
  class Dataset {
    table(id: string): Table;
    exists(callback: Function): void;
    create(callback: Function): void;
  }
  class Table {
    insert(rows: Object, options: Object, callback: Function): void;
  }
  class GCloud {
    storage (options: any): Storage;
  }
  function gcloud (options: any): GCloud;
  function bigquery (options?: any): BigQuery;
  function storage (options?: any): Storage;
  function pubsub (options?: any): PubSub;
}
```

All `.ts` files are in source control and the generated `.js` and `.js.map` files are located in `dist/` which is where `npm start` runs via `tsc && node dist/index.js`. The `dist/` dir is not in source control but it does exist in the running container.

I tried to use `import * as debug from '@google/cloud-debug'` as mentioned in the guide, but that gave unknown module errors. So we're just using the following (which remains the same after transpilation):

```
require('@google/cloud-trace').start();
require('@google/cloud-debug');
```

**Comment by Splaktar** [comment]
The changes in https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/pull/159 may be required for this to work.

**Comment by Splaktar** [comment]
I tried using the latest changes from @DominicKramer in https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/pull/159 and I was able to hit breakpoints!

One note, I put a breakpoint in my `.ts` file on line 39 and then when it hit, it was moved to line 35 (which is in some completely different logic which didn't run). So I was able to inspect the variables and do some basic debugging, but there still seems to be a disconnect between the line number in the TypeScript file and the JS file with source maps enabled (in separate `.js.map` files).

**Comment by DominicKramer** [comment]
@Splaktar Pull request [#159](https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/pull/159) now contains a possible fix for the issue you were seeing.  Can you verify that the fix addresses the problem you were seeing?  Thanks.

**Comment by Splaktar** [comment]
Thanks. I will take a look after dinner.

**Comment by Splaktar** [comment]
@DominicKramer confirmed. That fixed it. Breakpoint hit and it remained at the same line. Thank you!

**Comment by DominicKramer** [comment]
No problem.  I'm glad to help.

**Comment by matthewloring** [comment]
The latest release includes the changes from https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/pull/159. It sounds like these changes were able to get things working for you. Closing this for now but feel free to reopen if you have any additional questions.
