### ISSUE TITLE
Configuration options?

### ISSUE THREAD

**Issue by arbesfeld** [GoogleCloudPlatform/cloud-debug-nodejs#163]
I am seeing this error in my App Engine project:

```
(Locals and arguments are only displayed for the top `config.capture.maxExpandFrames` stack frames.
```

Is this expected? How do I configure these options?

**Comment by ofrobots** [comment]
For now you can look at the instructions here: https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/pull/164. We are working on a better solution however wherein we will accept configuration at module start.

**Comment by matthewloring** [comment]
With the latest release, configuration can be provided when the agent is started (https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/pull/167). Configuration is covered in our readme here: https://github.com/GoogleCloudPlatform/cloud-debug-nodejs#configuration. I'm going to close this for now but feel free to reopen if you have additional questions.
