### ISSUE TITLE
Failed to re-register debuggee XXX: ApiError: Precondition check failed.

### ISSUE THREAD

**Issue by stoianchoo** [GoogleCloudPlatform/cloud-debug-nodejs#263]
GAE Flex NodeJS

`"node": ">6.4.0"`

`require('@google-cloud/debug-agent').start({ allowExpressions: true });`
after the trace-agent requre.

I get an error:
ERROR:@google-cloud/debug-agent: Failed to re-register debuggee project-name-redacted: ApiError: Precondition check failed.

_mod-edit: redacted project name._

**Comment by stoianchoo** [comment]
The error is gone now. I think there was an update to the debugger and now I see the "logpoint" functionality that I don't remember seeing before.

Still the error message did not help in understanding the problem.

**Comment by ofrobots** [comment]
@stoianchoo Thanks for the report & feedback. We're looking at how to improve the error message.

I am very curious about the error. A few questions:
* Did this occur at application startup, or sometime later?
* What version of the debug-agent are you using?

**Comment by stoianchoo** [comment]
@ofrobots Just in case you still need this info:
- Not sure exactly when it occurred but it was definitely occurring when the instance was restarted.
- "@google-cloud/debug-agent": "^1.0.0"

**Comment by ofrobots** [comment]
Thanks! I believe this should be fixed by #265. We'll try to get that released into a new version of the module in the coming week.
