### ISSUE TITLE
Add docs explaining source map requirements

### ISSUE THREAD

**Issue by montmanu** [GoogleCloudPlatform/cloud-debug-nodejs#266]
Its a bit unclear from the documentation whether or not the application sources actually need to exist on disk within the runtime environment or whether cloud debug uses the remote sources (GCP repo, GH, BitBucket, etc) for resolving references.

For example, given the following source directory structure:

```
.
├── package.json
├── node_modules
├── src
│   ├── client
│   ├── components
│   ├── server
│   │   └── index.js
│   ├── etc...
```

and resulting build artifacts:

```
.
├── app
│   ├── package.json
│   ├── source-context.json
│   ├── source-contexts.json
│   ├── node_modules
│   ├── server
│   │   ├── main.js
│   │   └── main.js.map **
│   ├── etc...
```

Will debug be able to resolve references to source mapped sources (e.g., `./src/components/Foo/index.js`) or would the sources need to exist within the runtime environment?

_**  all individual application sources are bundled within `/app/server/main.js` with references to `./src/components/Foo/index.js` within `/app/server/main.js.map`_

**Comment by matthewloring** [comment]
When the debug agent receives a request to set a breakpoint it first checks whether the file in which the breakpoint is being set appears as a `source` in any source maps the agent can find in the runtime environment. That means that if you set a breakpoint in `index.js` through the cloud UI, `main.js` and `main.js.map` are present in the runtime, and `main.js.map` lists `index.js` as a source then this should work. I agree that this behavior should be better documented. Are you observing issues with breakpoints not being set correctly? Also, what tool are you using to produce this source transformation?

**Comment by matthewloring** [comment]
@montmanu Any additional information on this?

**Comment by matthewloring** [comment]
https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/pull/277 Should improve the documentation on source map support. I'm going to close this for now but feel free to re-open if you have additional questions.
