### ISSUE TITLE
Default column number for source-map may be 1

### ISSUE THREAD

**Issue by matthewloring** [GoogleCloudPlatform/cloud-debug-nodejs#27]
https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/blob/master/lib/v8debugapi.js#L125

Columns may be 1 indexed. Need to investigate.

**Comment by matthewloring** [comment]
I can't find any explicit documentation about column range with a cursory scan but the examples on their readme do include positions with column 0. (search for `column: 0` at https://github.com/mozilla/source-map/).

@ofrobots Is this sufficient evidence?

**Comment by ofrobots** [comment]
If the column is 0-indexed, shouldn't the line be 0-indexed too?

**Comment by matthewloring** [comment]
Looking through their tests, https://github.com/mozilla/source-map/blob/master/test/test-source-node.js#L101 for example, line 1 column 0 seems to be the default starting position for a breakpoint. It's not conclusive but the widespread use of column 0 and lack of any use of line 0 would suggest that lines are 1 indexed while columns are 0 indexed.

**Comment by ofrobots** [comment]
Digging further into the source.
https://github.com/mozilla/source-map/blob/ff05274becc9e6e1295ed60f3ea090d31d843379/lib/source-map-consumer.js#L537-L543:

```javascript
      if (aNeedle[aLineName] <= 0) {
        throw new TypeError('Line must be greater than or equal to 1, got '
                            + aNeedle[aLineName]);
      }
      if (aNeedle[aColumnName] < 0) {
        throw new TypeError('Column must be greater than or equal to 0, got '
                            + aNeedle[aColumnName]);
      }
```
Indeed, lines are 1-indexed and columns are 0-indexed.

**Comment by ofrobots** [comment]
I think we can close this.
