### ISSUE TITLE
Docs: Better documentation for available configuration options

### ISSUE THREAD

**Issue by jmdobry** [GoogleCloudPlatform/cloud-debug-nodejs#283]
While directing users to the library's source code for available configuration options will arguably give them the source of truth, it is quite a jarring experience when users on https://cloud.google.com/debugger/docs/setup/nodejs are redirected to a `.js` file on GitHub.

Can we please add a table of available configuration options to the README? 

OR

Can we please get some JSDoc reference docs (that include the available configuration options) published for this library?

Thanks

**Comment by ofrobots** [comment]
I agree. I think JSDoc might be a better option, and I think we can tackle this after the current migration to typescript completes.

**Comment by ofrobots** [comment]
@JustinBeckwith do we have a mechanism / paved-path to generate "jsdocs" for TypeScript repos across all the client libraries at this point? I am trying to figure out how we should solve this and whether this is unqiue to this repo or should be solved once globally across all?

**Comment by JustinBeckwith** [comment]
We really don't.  Tsdoc just isn't viable, as it's I'll maintained, and often behind on TypeScript version support.  As awful as it sounds. We've really been relying on jsdoc even in TypeScript 😱

This is one of those places where we could *really* use the node teams help.

**Comment by ofrobots** [comment]
Given that this needs to be solved generally across all repos, I am going to move this over to https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2853 and close this issue out.
