### ISSUE TITLE
vscode and node 8.8.1+ interaction

### ISSUE THREAD

**Issue by ggprod** [GoogleCloudPlatform/cloud-debug-nodejs#354]
I've found that when we moved our service from node v6.11.1 to v8.8.1 or v8.9.0 we can no longer debug our service locally if we include the debug-agent (vscode stops hitting breakpoints).  When I comment out the line

`// require('@google-cloud/debug-agent').start({ allowExpressions: true })`

our service can be debugged locally and vscode can once again hit breakpoints

**Comment by ofrobots** [comment]
This is interesting. I actually would have expected this to have worked before. My understand was that the V8 Debugging APIs are 'single session' at least some point in the past, so having two concurrent debuggers active sounds surprising.

But, if this used to work, we're definitely curious on how it did, and whether we ended up with a semver major changes on Node that caused it to break. We can take a investigate.

Can you provide more information on how you start your service – that is what command line options are you using to allow vscode debugger to connect?

Thanks for reporting.

**Comment by ggprod** [comment]
vscode runs a command like `node --inspect-brk=12888 src/server.js` to start debugging.

I didn't mean to imply that we have separate debug sessions.  It is just a single local debug session in vscode (when we attempt to debug our service locally).

We have the debug-agent included in our code via the line:
`require('@google-cloud/debug-agent').start({ allowExpressions: true })` and we didn't have to comment it out or remove it to be able to debug locally previously when we were using node v6.11.1 but now if we don't remove or comment it out with v8.8.1 or v8.9.0 and we attempt to debug locally then vscode debugger doesn't hit breakpoints

**Comment by ofrobots** [comment]
I can reproduce the issue. It seems that debug agent is able to work concurrently with the inspector on Node 6.x and 7.x, but is broken starting Node 8.0.0.

**Comment by ofrobots** [comment]
Apologies for losing track of this issue.

I have verified that the latest debug agent release no longer interferes with local debugging when tested with Node 8.11.x+ or Node 10.

Please give this another shot and re-open or comment if this is still an issue.
