### ISSUE TITLE
Gracefully handle unexpected source maps

### ISSUE THREAD

**Issue by montmanu** [GoogleCloudPlatform/cloud-debug-nodejs#366]
When encountering a source map that the agent doesn't expect (e.g., a css source map), the agent seem to fail to initialize. Here's a sample log entry:

```
ERROR:@google-cloud/debug-agent: Error processing the sourcemaps. Error: An error occurred while processing the sourcemap filesError: No sources listed in the sourcemap file public/vi-assets/main-b7c14129f872a062abe21d8edb364c0d.css.map
```

**Comment by DominicKramer** [comment]
Thanks for letting us know about this issue.  It is being addressed in PR #371 .

**Comment by DominicKramer** [comment]
`@google-cloud/debug-agent` version `2.3.2` addresses this issue.

**Comment by montmanu** [comment]
thank you!
