### ISSUE TITLE
Wrong types

### ISSUE THREAD

**Issue by agmontpetit** [GoogleCloudPlatform/cloud-debug-nodejs#367]
I'm using Node with TypeScript and I'm facing an issue with types when starting the debugger as suggested in the [Quick Start](https://github.com/GoogleCloudPlatform/cloud-debug-nodejs#quick-start) section:
```
import debugAgent = require('@google-cloud/debug-agent');
debugAgent.start({ allowExpressions: true });
```

It seems the type definition is wrong and more params (other than `allowExpressions`) are required:
```
Argument of type '{ allowExpressions: true; }' is not assignable to parameter of type 'DebugAgentConfig | StackdriverConfig'.
```

**Comment by DominicKramer** [comment]
Thank you for letting us know about this.  This issue is being addressed in PR #370.

**Comment by agmontpetit** [comment]
Thanks for the fix, @DominicKramer!

**Comment by DominicKramer** [comment]
@google-cloud/debug-agent version 2.3.1 addresses this issue.

**Comment by DominicKramer** [comment]
@agmontpetit Please let me know if you still have any issues using version 2.3.1.  Thanks.

**Comment by agmontpetit** [comment]
@DominicKramer It works perfectly! Thanks!

**Comment by DominicKramer** [comment]
No problem.  I'm glad to help.
