### ISSUE TITLE
Occasional stackdriver errors when not debugging

### ISSUE THREAD

**Issue by ggprod** [GoogleCloudPlatform/cloud-debug-nodejs#405]
We are occasionally seeing errors like (even though there is no debugging occurring):

ERROR:@google-cloud/debug-agent: Unable to fetch breakpoints – stopping fetcher Error: ESOCKETTIMEDOUT

ERROR:@google-cloud/debug-agent: Failed to re-register debuggee geoffrey-peddle-test: Error: ESOCKETTIMEDOUT

ERROR:@google-cloud/debug-agent: Unable to fetch breakpoints – stopping fetcher Error: unable to list breakpoints, status code 401

**Comment by ofrobots** [comment]
Hi @ggprod, Can you specify some details:

* The environment in which you're running your application (AppEngine, GKE, Cloud Functions, Locally, etc.)
* The versions of @google-cloud/debug-agent and google-auth-library that your application ends up using.

**Comment by ggprod** [comment]
Sure, this is running on app engine flexible and the debug-agent version is 2.2.2, the google-auth-library is 0.12.0

**Comment by ggprod** [comment]
ok, sounds good, I'll try that.. thanks @ofrobots !

**Comment by ggprod** [comment]
Seems like upgrading to latest debug-agent doesn't uprev google-auth-library (yarn.lock suggests 0.12 is still the highest version after new debug-agent).. but perhaps it will still solve our issue

**Comment by ofrobots** [comment]
@ggprod you're right. It seems that we updated the dependency on `@google-cloud/common` recently, and this hasn't been released yet. We'll try to publish a new version tomorrow.

**Comment by DominicKramer** [comment]
There are some test errors on the master branch related to changes in the dependencies.  I will need to fix those before making a release, and thus the release probably won't happen today.  I will keep you up-to-date on an ETA.

**Comment by DominicKramer** [comment]
Version 2.4.0 has been released and should resolve this issue.  If you are still experiencing problems, please let me know.  Thanks.
