### ISSUE TITLE
Debugging transpiled code changes the breakpoint line number

### ISSUE THREAD

**Issue by xp500** [GoogleCloudPlatform/cloud-debug-nodejs#417]
After applying https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/pull/402 locally, I managed to get the stackdriver debugger to work. The problem is that if I set a breakpoint on a typescript file the breakpoint line will change when the breakpoint hits

Before hitting
![image](https://user-images.githubusercontent.com/4530263/38971821-520798f4-4373-11e8-9c89-2c463892ecb6.png)
After hitting
![image](https://user-images.githubusercontent.com/4530263/38971838-5cb528ac-4373-11e8-8ad9-4197c736cd79.png)

I believe that the problem is on https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/blob/master/src/agent/v8/legacy-debugapi.ts#L461 and https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/blob/master/src/agent/v8/inspector-debugapi.ts#L469 which changes the line number to the one set in the call frames. The problem is that the call frames refer to another file (the javascript file) and not the original typescript file where I set the breakpoint.

**Comment by DominicKramer** [comment]
Thank you for letting us know about this and for looking into this.  As we work through this, we will keep this thread updated with status updates.

**Comment by richardfickling** [comment]
This has an additional impact which is that breakpoints set on a line after compiled file ends won't work at all. For example, my `user.ts` file has 519 lines. Compiled as `user.js`, it has 434 lines. I can't add a breakpoint to `user.ts` after line 434

![image](https://user-images.githubusercontent.com/1130084/40577867-84f65290-60c0-11e8-962e-ff2e8e5aece3.png)

**Comment by DominicKramer** [comment]
Thanks for letting us know about this.  Based on this feedback, I have updated the priority of this issue.

**Comment by DominicKramer** [comment]
This issue has been fixed and released in version 2.6.0.  If you are still encountering problems, please let me know.  Thanks.

**Comment by richardfickling** [comment]
@DominicKramer  The issue I reported above (unable to add breakpoints after end of original file) is still happening, although the original submitted issue (breakpoints moving) seems to be fixed.
