### ISSUE TITLE
2.5.0: nginx connection refused while connecting to upstream (502)

### ISSUE THREAD

**Issue by adriaanmeuris** [GoogleCloudPlatform/cloud-debug-nodejs#420]
hi, since updating from `2.4.0` to `2.5.0` we're unable to get our application running on GAE flex. Our instance is live, but not ready - basically the same situation as described in [this issue on serverfault](https://serverfault.com/questions/873497/502-connection-refused-while-connecting-to-upstream-modify-nginx-upstream-on-g). 

Our logs show these errors on every request:
<img width="667" alt="nginx-gae" src="https://user-images.githubusercontent.com/16230038/39305372-3480f5ce-495d-11e8-87fa-005ca44ec0ad.png">

output is a bad gateway from Nginx, so the app does not get started:
<img width="249" alt="502" src="https://user-images.githubusercontent.com/16230038/39305414-4d75f016-495d-11e8-8d5c-db71e16c3fb2.png">

Simply reverting to `2.4.0` resolves the issue. We're using Node `8.9.4` and we start the debug agent immediately when starting the app like this:
```js
require('@google-cloud/debug-agent').start({
    // debug agent settings
    capture: {maxFrames: 20, maxProperties: 100}
  });
```

any ideas?

**Comment by adriaanmeuris** [comment]
had a look at the StackDriver Error Reporting - does following issue could be the cause?

```
TypeError: semver.coerce is not a function
    at Object.satisfies (/app/node_modules/@google-cloud/debug-agent/build/src/agent/util/utils.js:181:33)
    at willUseInspector (/app/node_modules/@google-cloud/debug-agent/build/src/agent/v8/debugapi.js:22:29)
    at Object.<anonymous> (/app/node_modules/@google-cloud/debug-agent/build/src/agent/v8/debugapi.js:28:5)
    at Module._compile (module.js:643:30)
```

**Comment by DominicKramer** [comment]
The Docker image used with `gcloud app deploy`, when a custom Dockerfile is not being used, is based on `gcr.io/google-appengine/nodejs`.

The `gcr.io/google_appengine/nodejs` image is the old name (Note: the `_` compared to the `-`).  I would suggest using the `gcr.io/google-appengine/nodejs` image.

I have not used `pm2`, and so I don't know off-hand what to suggest with respect to it.

The 502 errors suggest, though, that perhaps the app is failing to start.  If the app is crashing on startup, Stackdriver logs should be able to help to determine why.  If there are logs indicating a failure or crash caused by the debug agent (or another Google library or agent) it would help us identify the underlying problem.

**Comment by DominicKramer** [comment]
Sorry, I just saw your most recent comment after I posted my last comment.  Yes, the problem with `semver.coerce` does look like it could be the underlying cause.  I will need to investigate, however, why `semver.coerce` is not a function.  What does `npm list | grep semver` return for you?

**Comment by adriaanmeuris** [comment]
Great catch on the Docker base image! No problem - we keep using `2.4.0` for now.

Output of `npm list | grep semver`:
```
│ ├── semver@5.4.1
│ │ │ ├── semver@5.4.1 deduped
│ ├── semver@5.4.1 deduped
│ │     └── semver@5.4.1 deduped
│ │ │   ├── semver@5.3.0
│ ├── semver@5.4.1 deduped
│ │ └── semver@5.4.1 deduped
│ ├── semver@5.4.1 deduped
│   ├── semver@5.4.1 deduped
│ │ │ └── semver@5.4.1 deduped
│ ├── semver@5.5.0

```

**Comment by DominicKramer** [comment]
This looks like an error specific to the debug agent since it requires semver `^5.1.0` but that version does not include the the `coerce` function.  I will get a fix out as soon as I can.  Thanks again.

**Comment by adriaanmeuris** [comment]
work like a charm, thanks!

**Comment by DominicKramer** [comment]
No problem, and thanks for filing the issue.
