### ISSUE TITLE
Deprecated: vm.runInDebugContext is not a function

### ISSUE THREAD

**Issue by sabrehagen** [GoogleCloudPlatform/cloud-debug-nodejs#503]
`@google-cloud/debug-agent@2.6.0` uses `runInDebugContext` which is now [deprecated](https://nodejs.org/docs/latest-v9.x/api/vm.html#vm_vm_runindebugcontext_code), causing code running in node v10 to crash.

**Comment by ofrobots** [comment]
@sabrehagen We use the inspector API on Node 10+. The `runInDebugContext` path should only get used on earlier versions of Node.

https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/blob/d0237356d9edba9c42ee7912db43c501bf5c3d6d/src/agent/v8/debugapi.ts#L45-L56

What is the precise version of Node you are using, and can you share the stack trace from the crash?

**Comment by ofrobots** [comment]
Very bizarre. Can you share the dependency section of your package.json file? I cannot reproduce this on my test case as follows:

* Create blank directory `debug-test`
* `npm init -y`
* `npm install @google-cloud/debug-agent'
* Create index.js with

```js
require('@google-cloud/debug-agent').start();

setTimeout(_=>_, 10000);
```
Run with: `GOOGLE_APPLICATION_CREDENTIALS=<keyfile> GCLOUD_PROJECT=<project> node --max-old-space-size=6144 index.js`

This seems to work okay. Perhaps I end up getting a different version of some dependency module that what you are seeing?

**Comment by ofrobots** [comment]
@sabrehagen with with a lot of head-scratching, we don't see why you're seeing this. We have created a branch on the repo with some debug log statements. Would you be able to give it a try? It might give us some clues about what is going wrong.

Install the module from the branch:

```bash
$ npm install git://github.com/GoogleCloudPlatform/cloud-debug-nodejs#debug-legacy-require
```
It should produce output of the form:
```
willUseInspector(undefined) => true
loading inspector-debugapi. process.version is v10.6.0
```

Then run it with your app. Let us know what output you get.

**Comment by ofrobots** [comment]
Is there a chance you're using a bundler like webpack or rollup that may be evaluating a path that is actually not reachable in reality?
