### ISSUE TITLE
Node.js apps that are sub-directories of the git repository don't work.

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-debug-nodejs#51]
Scenario:

1. Git repository with a directory Server/ that contains a Node.js app. i.e. `Server/app.js` and `Server/app.yaml` exist.
1. Host the repository in a gcloud source repo.
1. Deploy the app, or copy `Server/*` to `/tmp/app` and run it locally from there.

Once deployed the path to app.js is `/app/app.js`. But to the Debug UI, this is `Server/app.js`.

Immediate goal: in this scenario we should be able to set a breakpoint in app.js without being confused.

Secondary goal: consider the following directory layout:
`Server/app.js` -> `/app/app.js`
`Server/foo/app.js`-> `/app/foo/app.js`
`Server/app/app.js` -> `/app/app/app.js`

In such an app, we should be able to set the breakpoint in the correct app.js when the server sets a breakpoint in `Server/app.js`, `Server/app/app.js`. We should report an error when the server asks for a breakpoint in `app.js`. We need test cases for these scenario.

**Comment by matthewloring** [comment]
The concern is that they have a directory structure such as:

`Server/app.js` -> `/app.js`
`Server/Server/app.js` -> `/Server/app.js`

When requesting to set a breakpoint in `Server/app.js` we will incorrectly attribute it to the code that was copied from `Server/Server/app.js`. If we could see all of the code on the server we could construct a map from server file names to executing file names but I don't believe it is possible to construct this map soundly in all cases starting only with a single server file name. It would be possible to build the map if we assume that path components are not repeated (such as nested directories with the name `Server`) but we would be unable to detect when this assumption is violated and would silently break and do the wrong thing. Alternatively, we could ask the user to provide us the mapping that should be used (for the above example they could provide `Server/` -> `/`) but this would help from the UI as well as a syntax for expressing mappings.

For now, I can add a heuristic that checks to see if there is only a single file with the provided name regardless of path but this will only be a slight improvement over the existing logic. Let me know what you think about the above options.

**Comment by ofrobots** [comment]
>  It would be possible to build the map if we assume that path components are not repeated (such as nested directories with the name Server)

I don't think we can assume this.

I think it would be reasonable to assume that the deployed directory tree is a strict subset of the git repo. In the scenario you pasted, the server would request either a breakpoint in `Server/Server/app.js` or `Server/app.js`. Since it is not possible to uniquely identify which file this refers to, I think it would be fair to return an error in this scenario.

> For now, I can add a heuristic that checks to see if there is only a single file with the provided name regardless of path but this will only be a slight improvement over the existing logic. Let me know what you think about the above options.

I think we can do a better heuristic if we assume two things:
1. deployed directory is a strict subset.
2. The working-directory at startup is the same directory as the package.json.

But still, there are cases where this has false positives. How about this: in cases where things are ambiguous, how about if we asked the user to give us a file name for a file in a different directory. Comparing the two paths will give an idea about what the app-root is relative to git-root. 

Alternatively, we should give them the list of files we might thing things possibly match, and tell them to run with an environment variable specifying the app-root.

WDYT?

**Comment by matthewloring** [comment]
@ofrobots #52 should solve both immediate and secondary goals and there are pre-existing tests to guard against the scenario you describe (see test/test-v8debugapi.js#129). Please confirm and I can close this bug.

**Comment by ofrobots** [comment]
Thanks for fixing.
