### ISSUE TITLE
Need a test-case to catch repo issues like in #55

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-debug-nodejs#56]
See: #55.

**Comment by matthewloring** [comment]
@ofrobots Does the [relative repository paths test](https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/blob/master/test/standalone/test-env-relative-repository-path.js) cover this case? It sets a breakpoint at a non-existent path that is normalized using the repo root hint from the environment variable so if the incorrect path were being used this test should fail.

**Comment by ofrobots** [comment]
Can you verify that the mentioned tests fails if you reverse #55? If the test starts failing then we have our answer.
