### ISSUE TITLE
Debugger no longer stops on line 1 breakpoints in Node 5.2 (works 5.1)

### ISSUE THREAD

**Issue by matthewloring** [GoogleCloudPlatform/cloud-debug-nodejs#61]

**Comment by matthewloring** [comment]
@ofrobots V8 version is the same between these node versions. Maybe the script preamble changed? I can investigate this but do you have any initial thoughts?

**Comment by ofrobots** [comment]
No initial thoughts. How did you find this issue? Hopefully one of our tests failed. If not, can we add that test?

**Comment by matthewloring** [comment]
Yup, test failure, been increasing test coverage and one test started failing since the last merge in a file I didn't touch.

**Comment by matthewloring** [comment]
The wrapping went from (v5.1.1):
(function (exports, require, module, __filename, __dirname) { <user code>\n});
to (v5.2):
(function (exports, require, module, __filename, __dirname) {\n<user code>\n});

We will have to apply the "☃ tactic" only for versions less than 5.2.

**Comment by ofrobots** [comment]
For posterity, this was triggered by a changed in Node.js 5.2 that breaks V8 debug API: https://bugs.chromium.org/p/v8/issues/detail?id=4620. This is now fixed in Node.js 5.3.0.
