### ISSUE TITLE
Add a test w/ Node 0.10

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-debug-nodejs#7]
We do not support the 0.10, but we should report an error to the UI when a breakpoint is set.

**Comment by matthewloring** [comment]
@ofrobots Is https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/blob/master/lib/debuglet.js#L30 there because 0.10 hasn't been tested or is there a stronger reason that this requires >0.12?

**Comment by ofrobots** [comment]
There is a stronger reason. With v0.10 there is a permanent performance hit
if the debugger is active. Furthermore the user needs to run with a command
line option to enable the debugger.

**Comment by matthewloring** [comment]
Closing this since the package doesn't install on 0.10 (npm doesn't support package namespaces at that version).
