### ISSUE TITLE
Invalid value at breakpoints using GKE.

### ISSUE THREAD

**Issue by Jakedavies** [GoogleCloudPlatform/cloud-debug-nodejs#96]
I get the following in my logs using the node cloud debugger in Kubernetes on GKE, I have the cloud platform enabled for the cluster. 

This occurs after I set a breakpoint in the application, and then hit that piece of code.

`[ { message: 'Invalid value at \'breakpoint.variable_table[10].members[1].name\' (TYPE_STRING), 0\nInvalid value at \'breakpoint.variable_table[10].members[2].name\' (TYPE_STRING), 1\nInvalid value at \'breakpoint.variable_table[10].members[3].name\' (TYPE_STRING), 2\nInvalid value at \'breakpoint.variable_table[10].members[4].name\' (TYPE_STRING), 3\nInvalid value at \'breakpoint.variable_table[10].members[5].name\' (TYPE_STRING), 4\nInvalid value at \'breakpoint.variable_table[10].members[6].name\' (TYPE_STRING), 5\nInvalid value at \'breakpoint.variable_table[10].members[7].name\' (TYPE_STRING), 6\nInvalid value at \'breakpoint.variable_table[10].members[8].name\' (TYPE_STRING), 7\nInvalid value at \'breakpoint.variable_table[10].members[9].name\' (TYPE_STRING), 8\nInvalid value at \'breakpoint.variable_table[10].members[10].name\' (TYPE_STRING), 9\nInvalid value at \'breakpoint.variable_table[10].members[11].name\' (TYPE_STRING), 10\nInvalid value at \'breakpoint.variable_table[10].members[12].name\' (TYPE_STRING), 11\nInvalid value at \'breakpoint.variable_table[10].members[13].name\' (TYPE_STRING), 12\nInvalid value at \'breakpoint.variable_table[10].members[14].name\' (TYPE_STRING), 13\nInvalid value at \'breakpoint.variable_table[10].members[15].name\' (TYPE_STRING), 14\nInvalid value at \'breakpoint.variable_table[10].members[16].name\' (TYPE_STRING), 15\nInvalid value at \'breakpoint.variable_table[10].members[17].name\' (TYPE_STRING), 16\nInvalid value at \'breakpoint.variable_table[10].members[18].name\' (TYPE_STRING), 17\nInvalid value at \'breakpoint.variable_table[10].members[19].name\' (TYPE_STRING), 18\nInvalid value at \'breakpoint.variable_table[10].members[20].name\' (TYPE_STRING), 19\nInvalid value at \'breakpoint.variable_table[10].members[21].name\' (TYPE_STRING), 20\nInvalid value at \'breakpoint.variable_table[10].members[22].name\' (TYPE_STRING), 21\nInvalid value at \'breakpoint.variable_table[10].members[23].name\' (TYPE_STRING), 22\nInvalid value at \'breakpoint.variable_table[10].members[24].name\' (TYPE_STRING), 23',`

**Comment by ofrobots** [comment]
Thanks for reporting the issue. Can you confirm the version of the `@google/cloud-trace` module you are using? Also, is this a recent behaviour change, or is this the first time you have tried this, and got these errors?

**Comment by ofrobots** [comment]
err... I meant the version of @google/cloud-debug.

**Comment by ofrobots** [comment]
Can you also confirm the version of Node.js you are using?

**Comment by Jakedavies** [comment]
"@google/cloud-debug": "^0.7.0",
Nodejs version 5.1

**Comment by ofrobots** [comment]
Thanks. This should be fixed by #98. We will try to get a release out next week with this fix.
